[package]
name = "curreny-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde = { version= "1.0.136", features = ["derive"] }
rusty-money = { version = "0.4.1", features = ["iso"] }
rust_decimal = "1.23"
rust_decimal_macros = "1.23"




